name: flesk-to-amazon
env:
  EB_PACKAGE_S3_BUCKET_NAME: "toha-github-actions-test"
  EB_APPLICATION_NAME: "github-actions-test"
  EB_ENVIRONMENT: "flesk-env"
  DEPLOY_PACKAGE_NAME: "flask-app-${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"

on:
  push:
    branches: [ main ]

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    
    - name: Git clone our repo
      uses: actions/checkout@v2
    
    - name: Create zip deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}

    - name: Copy deployment package to S3 backet
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}

    - name: Print happy message
      run: echo "CI pipline finished successfuly"
